from . import property_property
from . import property_flat
from . import property_room
from . import property_room_type
from . import property_tenant
from . import property_occupant
from . import property_agreement
from . import property_collection
from . import property_invoice
from . import property_dashboard
from . import property_other_charges
from . import property_outstanding_dues
from . import property_statement
